name:                openapi-test
version:             0.1.0.0
github:              "tvestelind/openapi-test"
license:             BSD3
author:              "Tomas Vestelind"
maintainer:          "tomas.vestelind@gmail.com"
copyright:           "none"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            hobby-project

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tvestelind/openapi-test#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - optparse-applicative
    - aeson
    - Spock
    - text
    - uuid
    - feed
    - filepath
    - directory
    - containers

executables:
  openapi-test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - openapi-test

tests:
  openapi-test-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - openapi-test
