openapi: 3.0.0
info:
  title: Kaustik Simple RSS Backend
  description: Kaustik's simple RSS backend for our programming task
  version: 1.0.0
servers:
  - url: localhost/api
paths:
  /feeds:
    get:
      description: Get all RSS feeds
      responses:
        '200':
          description: A map of feeds from RSSChannelId to RSSChannel
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/RSSChannel'
                example:
                  - 12345678-1234-1234-1234-123456789012:
                      name: A jolly good blag
                      items:
                        - title: My fine blog post
                          content: Hello World!
                        - title: A jolly good blag past
                          content: Hello ye old world
  '/feeds/{channelid}':
    get:
      description: Get one RSS feed
      parameters:
        - name: channelid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/RSSChannelId'
      responses:
        '200':
          description: One found RSS feed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RSSChannel'
        '400':
          description: Supplied id was not a correct UUID
        '404':
          description: No RSS feed found for that channel id
components:
  schemas:
    RSSChannel:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/RSSChannelId'
        name:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/RSSItem'
      required:
        - name
        - items
      example:
        name: A jolly good blag
        items:
          - title: My fine blog post
            content: Hello World!
          - title: A jolly good blag past
            content: Hello ye old world
    RSSChannelId:
      type: string
      format: uuid
      example: 12345678-1234-1234-1234-123456789012
    RSSItem:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      required:
        - title
        - content
      example:
        - title: My fine blog post
          content: Hello World!
        - title: A jolly good blag past
          content: Hello ye old world
