openapi: 3.0.0
info:
  title: Kaustik Simple RSS Backend
  description: Kaustik's simple RSS backend for our programming task
  version: 0.0.1
servers: 
  - url: localhost/api
paths:
  /feeds:
    get:
      description: Get all RSS channel feeds
      responses:
        '200':
          description: A list of RSS channel feeds
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RSSChannel'
  /feeds/{channelid}:
    get:
      description: Get one RSS channel feed
      parameters:
        - name: channelid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/RSSChannelId'
      responses:
        '200':
          description: Returned a found RSS feed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RSSChannel'
        '400':
          description: No RSS feed found for that channel id
components:
  schemas:
    RSSChannel:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/RSSChannelId'
        name:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/RSSItem'
      required:
        - id
        - name
        - items
      example:
        - id: 00000000-1111-1111-1111-123456789012
          name: My new blog about blogs
          items: []
        - id: 00000000-2222-2222-2222-123456789012
          name: A jolly good blag
          items:
            - id: 12345678-1234-1234-1234-123456789012
              title: My fine blog post
              content: Hello World!
            - id: 12345678-0000-0000-0000-123456789012
              title: A jolly good blag past
              content: Hello ye old world
    RSSChannelId:
      type: string
      format: uuid
      example: 12345678-1234-1234-1234-123456789012
    RSSItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        content:
          type: string
      required:
        - id
        - title
        - content
      example:
        - id: 12345678-1234-1234-1234-123456789012
          title: My fine blog post
          content: Hello World!
        - id: 12345678-0000-0000-0000-123456789012
          title: A jolly good blag past
          content: Hello ye old world